config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 resources :songs
#  get 'home/index'
  get 'home/about'
  root 'songs#index'
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about 
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/scroll
  #def scroll
  #end

  # GET /songs/new
  def new
    #@song = Song.new
    @song = current_user.songs.build
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    #@song = Song.new(song_params)
    @song = current_user.songs.build(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @song = current_user.songs.find_by(id: params[:id])
    redirect_to songs_path, notice: "Not Authorized to Edit This Song" if @song.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :artist, :youtubevideo, :lyrics, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/_footer.html.erb
   <br>
   <br>
   <br>
<footer class="bg-dark text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3 text-light"  style="background-color: #715d79;">
    © 2022
    <a class="text-light" href="https://roylouisgarcia.github.io/" target="_blank"><strong><i>Playlist Builder</i></strong> Created by NostradmsX</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #715d79;">
  <div class="container-fluid">
  <%= link_to 'Playlist Builder', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

       
        
        <% if user_signed_in? %>  
        
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, class:"nav-link" %>
             </li>
            <li class="nav-item">
                <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
            </li>
    <% else %>  
        
        <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %></li>
        <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %></li>
       


        <% end %>
        <li class="nav-item">
        <%= link_to 'About NostradmsX', home_about_path, class:"nav-link" %></li>

      </ul>
     <%#  <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
 %>    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="card">
  <h1 class="card-header">About NostradmsX</h1>
  <div class="card-body">


<p>NostradmsX is the pseudonym I started using way back during the prominence of AOL and Yahoo. I have varying genesis stories associated with this pseudonym.
</p><p>
No_Str_A = Altruism
</p><p>
It all started when I took probono projects and started using “no_str_a” (no strings attached) as signature and AOL account username. I later dropped the underscores and preferred being called “nostra”. Back then, I offered to create websites, graphic arts, and pamphlets for bands, churches, and non-profits. In return, I asked for permission to include my works for project submissions in school. So, I guess it is not entirely altruistic, but “enabling” people and businesses using technology became an ideal.
</p>
</div>
</div>

app/views/home/index.html.erb
<div class="card">
  <h1 class="card-header">Playlist Builder</h1>
  <div class="card-body">
  
  
<p>Music taste may be subjective but we can discover good music from one another. This app is created for Users who wants to curate their song playlists. This app is created using Ruby on Rails. </p>  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-primary alert-dismissible fade show d-flex align-items-center" role="alert">
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </svg>
  <div>
  <%= notice %>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Playlist Builder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render "home/header" %>
<div class="container"> 
<br/>
<% if notice %>
    <%= render 'layouts/alerts' %> 
<% end %>
 <%= yield %>

</div>


  <%= render "home/footer" %>
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :title, class:"form-control", placeholder:"Song Title"  %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :artist, class:"form-control", placeholder:"Artist Name"   %>
  </div>

  <br/>
  <div class="field form-group">
    <%= form.text_field :youtubevideo, class:"form-control", placeholder:"Youtube Link"   %>
  </div>

  <br/>
  <div class="field form-group">
    <%= form.text_field :lyrics, class:"form-control", placeholder:"Lyrics Link"   %>
  </div>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :song_user_id, class:"form-control", value: current_user.id, type: :hidden  %>
  </div>
  <br/>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p>
    <strong>Title:</strong>
    <%= song.title %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= song.artist %>
  </p>

  <p>
    <strong>Youtube Video:</strong>
     <%= song.youtubevideo %>  <%= link_to "Visit", song.youtubevideo, class: "btn btn-light btn-sm", target: "_blank" %>
  </p>

  <p>
    <strong>Lyrics:</strong>
     <%= song.lyrics %>  <%= link_to "Visit", song.lyrics, class: "btn btn-light btn-sm", target: "_blank" %>
    
  </p>
      <br>
</div>

app/views/songs/edit.html.erb
<h1>Editing song</h1>
<div class="box show">
<%= render "form", song: @song %>
</div>
<br>

<div>
  <%= link_to "Show this song", @song, class: "btn btn-light" %> 
<%= button_to "Destroy this song", @song, method: :delete, class: "btn btn-danger"  %>
  <%= link_to "Back to songs", songs_path, class: "btn btn-warning" %>
</div>

app/views/songs/index.html.erb
<div id="songs">
<% if user_signed_in? %>

<table class="table table-light table-striped table-bordered">
<thead class="thead-dark">
<tr>
  <th scope="col">Title
  </th>
  <th scope="col">Artist</th>
  <th scope="col"></th>
  <th scope="col"></th>
</tr>

</thead>

<tbody>
 <% @songs.each do |song| %>
<% if song.user == current_user %>
  <tr>
    <th scope="row"><%= link_to song.title, song %></th>
    <td><%= song.artist %></td>
    <td><%= link_to "Youtube", song.youtubevideo, class: "btn btn-danger btn-sm", target: "_blank" %></td>
    <td><%= link_to "Lyrics", song.lyrics, class: "btn btn-warning btn-sm", target: "_blank" %></td>
  </tr> 
  <% end %>
  <% end %>
</tbody>

</table>
<%= link_to "New song", new_song_path, class: "btn btn-primary" %>
<% else %>
<div class="card">
  <h1 class="card-header">Playlist Builder</h1>
  <div class="card-body">
  
  
<p>Ones taste in music may be subjective but we can help each other good music by simply sharing our favorite songs one playlist at a timer. This app is created for music lovers who want to curate their playlists and even share it to the public or friends. This app is created using Ruby on Rails. </p> <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %> </div>
</div>

<% end %>

</div>

app/views/songs/new.html.erb
<h1>Add Song Info</h1>
<div class="box show">
<%= render "form", song: @song %>
<br>
</div>

<div>
  <%= link_to "Back to songs", songs_path, class:"btn btn-secondary" %>
</div>

app/views/songs/scroll.html.erb
<div id="scroll">

<% counter = 0 %>
 <% @songs.each do |song| %>
 <% counter = counter + 1 %>
     <% if counter == 1 %>
      <div class="box show">  
         <%= render song %>
         </div>
         <% else %>
      <div class="box">  
     <%= render song  %>
     </div>
     <% end %>
 <% end %> 
</div>



<%= link_to "See All Songs", songs_path, class: "btn btn-primary" %>

app/views/songs/show.html.erb
<div class="box show">
<%= render @song %>
</div>
<div>
  <%= link_to "Edit this song", edit_song_path(@song), class: "btn btn-success" %> 
  <%= link_to "Back to songs", songs_path, class: "btn btn-warning" %>
<br/>
</div>